### ISSUE TITLE
中文乱码问题

### ISSUE THREAD

**Issue by FurryWolfX** [Jamling/SmartIM#9]
![](https://i.loli.net/2018/09/21/5ba4959c215b8.png)

OS: Deepin 15.7

```
java -version
Picked up _JAVA_OPTIONS:   -Dawt.useSystemAAFontSettings=gasp
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-2-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

**Comment by Jamling** [comment]
这个是因为系统JVM中没有相关的中文字体导致的。可以尝试在jre中将操作系统的字体文件夹链接到jre字体文件夹中。PS，在smartim相关的三个项目中好像有提过此issue，我有回复。

**Comment by oscWolfX** [comment]
> 这个是因为系统JVM中没有相关的中文字体导致的。可以尝试在jre中将操作系统的字体文件夹链接到jre字体文件夹中。PS，在smartim相关的三个项目中好像有提过此issue，我有回复。

谢谢回答，我用另一种方式解决了：

```
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'
```
